{% set name = "amazon_sagemaker_sql_editor" %}
{% set version = "0.1.19" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/amazon_sagemaker_sql_editor-{{ version }}.tar.gz
  sha256: 746319b4cd6b5bba430d02ad6d18ccee142938189c2f45d4456f1211cfe3644f

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 1
  overlinking_ignore_patterns:
    - "**/sql-language-server/node_modules/**"

requirements:
  host:
    - python {{ python_min }}
    - hatchling >=1.5.0
    - jupyterlab >=4.1,<5
    - hatch-nodejs-version
    - pip
    - hatch-jupyter-builder
  run:
    - python >={{ python_min }}
    - jupyterlab-lsp ==5.0.*
    - diskcache ==5.6.*
    - jupyter_server
    - botocore >=1.31.64,<2
    - aiobotocore >=2.7.0,<3
    - boto3 >=1.29.6,<2
    - sagemaker-jupyterlab-extension-common >=0.2.1,<1
    - amazon-sagemaker-sql-execution >=0.0.7,<1

test:
  imports:
    - amazon_sagemaker_sql_editor
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://pypi.org/project/amazon-sagemaker-sql-editor/
  summary: 'Package which provides sql editor functionalities for Sagemaker SQL extension'
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - sgganjo
    - aws-jasakshi
    - aakashmandavilli96
    - chad119
    - nileshvd
    - bhadrip
    - kumarnzt
    - gogakoreli
    - varun196
    - HariniNarayanan
